name: ui_prototype
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  http: ^1.2.2
  shared_preferences: ^2.5.5

  socket_io_client: ^3.0.2

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2

  google_generative_ai: ^0.4.0

  table_calendar: ^3.2.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  url_launcher: ^6.3.0
  emailjs: 4.0.0
  location: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true